name: Delete old workflow runs and clean package registry
on:
  push:
    branches:
      - 'master'
      - 'main'
  schedule:
    - cron: '0 0 1 * *'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 4

  cleanup-registry:
    runs-on: ubuntu-latest
    #container: ghcr.io/thefoundation-builder/docker-with-buildx:latest
    if: github.repository_owner == 'thefoundation-builder'
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: "${{ github.event.repository.name }}"
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
          ignore-versions: '.*(buildcache|baseimage)(|.*)'
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: "${{ github.event.repository.name }}"
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'false'
          ignore-versions: '.*(buildcache|baseimage)(|.*)'
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: "${{ github.event.repository.name }}"
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'false'
          ignore-versions: '.*(buildcache|baseimage)(|.*)'
